### ISSUE TITLE
ArrayList as a media of the taint? 

### ISSUE THREAD

**Issue by majestyhao** [secure-software-engineering/soot-infoflow-android#92]
Is arraylist considered as a media of the taint? 
I tested an opensource app (https://github.com/majestyhao/com.hectorone.multismssender_13_src)  and here is the code snippet: 
```
String[] numbers  = mContacts.getText().toString().split(",");
for (int i = 0; i < size; i++) {
			String newN = numbers[i].trim();
			newN = newN.replace(" ", "");
			if (!newN.equals("")
					&& PhoneNumberUtils.isWellFormedSmsAddress(newN)
					&& !phoneNumberConform.contains(newN)) {
				phoneNumberConform.add(newN);
                 }
}

numbers = new String[size];
numbers = phoneNumberConform.toArray(numbers);


for (int i = message_sent; i < chunk_max; i++) {
						message_sent++;
						String newN = numbers[i];
						manager.sendMultipartTextMessage(newN, null, messages,
								sentIntents, deliveryIntents);
}
```
I added \<android.widget.TextView: java.lang.CharSequence getText()\> -> _SOURCE_ into the SourcesAndSinks.txt and I wanted the array "numbers" to be the source. But the output of FlowDroid does not contain any related taint.

**Comment by StevenArzt** [comment]
This happened due to several bugs that have been fixed by now. Still, some optimizations are incompatible with this concrete app (rarely happens but does happen here). Please run FlowDroid with the --safemode option.

**Comment by majestyhao** [comment]
I tried it with --safemode option. But the output remain: 
```
Found a flow to sink virtualinvoke $r10.<android.telephony.SmsManager: void sendMultipartTextMessage(java.lang.String,java.lang.String,java.util.ArrayList,java.util.ArrayList,java.util.ArrayList)>($r15, null, $r18, $r31, $r30) on line 404, from the following sources:
	- $r32 = staticinvoke <android.app.PendingIntent: android.app.PendingIntent getBroadcast(android.content.Context,int,android.content.Intent,int)>($r0, 0, r39, 0) (in <com.hectorone.multismssender.MultiSmsSender: void sendMessage(android.os.Handler)>)
		on Path [$r32 = staticinvoke <android.app.PendingIntent: android.app.PendingIntent getBroadcast(android.content.Context,int,android.content.Intent,int)>($r0, 0, r39, 0), virtualinvoke $r30.<java.util.ArrayList: boolean add(java.lang.Object)>($r32), virtualinvoke $r10.<android.telephony.SmsManager: void sendMultipartTextMessage(java.lang.String,java.lang.String,java.util.ArrayList,java.util.ArrayList,java.util.ArrayList)>($r15, null, $r18, $r31, $r30)]
	- specialinvoke $r0.<android.app.Activity: void onActivityResult(int,int,android.content.Intent)>($i0, $i1, $r1) (in <com.hectorone.multismssender.MultiSmsSender: void onActivityResult(int,int,android.content.Intent)>)
		on Path [specialinvoke $r0.<android.app.Activity: void onActivityResult(int,int,android.content.Intent)>($i0, $i1, $r1), return, specialinvoke $r21.<com.hectorone.multismssender.MultiSmsSender$4: void <init>(com.hectorone.multismssender.MultiSmsSender)>($r15), $r0.<com.hectorone.multismssender.MultiSmsSender$4: com.hectorone.multismssender.MultiSmsSender this$0> = $r1, return, virtualinvoke $r21.<com.hectorone.multismssender.MultiSmsSender$4: void onClick(android.view.View)>($r22), $r2 = $r0.<com.hectorone.multismssender.MultiSmsSender$4: com.hectorone.multismssender.MultiSmsSender this$0>, $r5 = $r2.<com.hectorone.multismssender.MultiSmsSender: com.hectorone.multismssender.MultiSmsSender$MessageSenderThread mThreadSender>, virtualinvoke $r5.<com.hectorone.multismssender.MultiSmsSender$MessageSenderThread: void start()>(), $r1 = $r0.<com.hectorone.multismssender.MultiSmsSender$MessageSenderThread: com.hectorone.multismssender.MultiSmsSender this$0>, virtualinvoke $r1.<com.hectorone.multismssender.MultiSmsSender: void sendMessage(android.os.Handler)>($r2), $r21 = virtualinvoke $r0.<com.hectorone.multismssender.MultiSmsSender: android.content.ContentResolver getContentResolver()>(), $r22 = virtualinvoke $r21.<android.content.ContentResolver: android.net.Uri insert(android.net.Uri,android.content.ContentValues)>($r22, $r19), $r23 = virtualinvoke $r22.<android.net.Uri: java.util.List getPathSegments()>(), $r24 = interfaceinvoke $r23.<java.util.List: java.lang.Object get(int)>(1), $r15 = (java.lang.String) $r24, $r16 = virtualinvoke $r15.<java.lang.String: java.lang.String[] split(java.lang.String)>(","), $r15 = $r16[$i4], $r15 = virtualinvoke $r15.<java.lang.String: java.lang.String trim()>(), $r15 = virtualinvoke $r15.<java.lang.String: java.lang.String replace(java.lang.CharSequence,java.lang.CharSequence)>(" ", ""), virtualinvoke $r3.<java.util.ArrayList: boolean add(java.lang.Object)>($r15), $r27 = virtualinvoke $r3.<java.util.ArrayList: java.lang.Object[] toArray(java.lang.Object[])>($r16), $r16 = (java.lang.String[]) $r27, $r15 = $r16[$i7], virtualinvoke $r10.<android.telephony.SmsManager: void sendMultipartTextMessage(java.lang.String,java.lang.String,java.util.ArrayList,java.util.ArrayList,java.util.ArrayList)>($r15, null, $r18, $r31, $r30)]
```

**Comment by StevenArzt** [comment]
Did you update soot-infoflow-android? I also changed the SourcesAndSinks.txt file. The "onActivityResult" method should not be in there, that was a mistake. It leads to serious over-tainting and the effects of such callbacks are handled differently anyway, making this entry unnecessary. If you remove this line (or just take the version of SourcesAndSinks.txt that I have committed), it should work.

**Comment by majestyhao** [comment]
It works! Thanks. 

One more question, FlowDroid still cannot handle multi-threading?

**Comment by majestyhao** [comment]
And I also found the output would be incorrect if use "--pathalgo contextsensitive" and "--safemode" simultaneously, is the safe mode necessarily powerful than context sensitive mode?

**Comment by majestyhao** [comment]
One more strange thing happens, I got 
```
[main] INFO soot.jimple.infoflow.Infoflow - The sink staticinvoke <android.util.Log: int i(java.lang.String,java.lang.String)>("MultiSmsSender", $r15) on line 259 in method <com.hectorone.multismssender.MultiSmsSender: void sendMessage(android.os.Handler)> was called with values from the following sources:
[main] INFO soot.jimple.infoflow.Infoflow - - $r12 = virtualinvoke $r11.<android.widget.TextView: java.lang.CharSequence getText()>() on line 254 in method <com.hectorone.multismssender.MultiSmsSender: void sendMessage(android.os.Handler)>
[main] INFO soot.jimple.infoflow.Infoflow - - $r12 = virtualinvoke $r11.<android.widget.TextView: java.lang.CharSequence getText()>() on line 267 in method <com.hectorone.multismssender.MultiSmsSender: void sendMessage(android.os.Handler)>
```
From the code: 
```
public void sendMessage(Handler handler) {
		String message                      = mEditor.getText().toString();

		// HERE
		Log.i(DEBUG_TAG, "FACTOR 0 HERE" + message);
String[] numbers                     = mContacts.getText().toString().split(",");
}
```

**Comment by StevenArzt** [comment]
FlowDroid should be able to handle Multithreading using the Java thread API. Do you have a concrete example for which it cannot handle multithreading? In your example, the leak happens inside a thread (started after a button click) and the leak is detected just fine. We just serialize threads, so we assume that all the actions of a thread happen directly when the thread is started instead of asynchronously. In most cases, this yields the same set of results as interleaved threads.

Do you have an example for the incorrect output when using the contextsensitive path algorithm? I used it for my tests and it worked.

Since you are reading data from a standard text field, keep in mind that you need to tell FlowDroid to treat all UI elements as sources, not only password fields. My complete argument list is:

```
"D:\app-debug.apk" "D:\Tools\adt-bundle-windows-x86_64-20140321\sdk\platforms" --layoutmode all --pathalgo contextsensitive --safemode
```

The second effect (the two sources from different lines) happen if you don't specify the context-sensitive path algorithm. It's a tradeoff: The context-sensitive algorithm is more precise as it can distinguish the two calls to getText(), but it takes more time.

**Comment by majestyhao** [comment]
All right, my mistake. Thank you.
